### ISSUE TITLE
Cannot download annotation

### ISSUE THREAD

**Issue by yifan-h** [amazon-science/street-reasoning#1]
Hi,

Thanks for the wonderful work! However, it seems that the download link for annotations doesn't work. Here is the error message:

    Downloading original AQUA-RAT...
    Downloading original AR-LSAT...
    Merging original AQUA-RAT with reasoning graph annotations...
    data/aqua_rat/aqua_rat_graph_annotation_train.jsonl
    Traceback (most recent call last):
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/run_street_data_generation.py", line 79, in <module>
        main()
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/run_street_data_generation.py", line 76, in main
        merge_with_reasoning_graph_data()
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/run_street_data_generation.py", line 68, in merge_with_reasoning_graph_data
        aqua_rat_data = dataset_utils.AquaRatData()
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/utils/dataset_utils.py", line 112, in __init__
        self.load_graph_annotations()
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/utils/dataset_utils.py", line 77, in load_graph_annotations
        self.graph_annotations[split] = utils.load_from_jsonl_file(path)
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/utils/utils.py", line 36, in load_from_jsonl_file
        return [json.loads(line) for line in fh.readlines() if line]
      File "/cluster/work/sachan/yifan/data/cg_reasoning/street/street-reasoning-main/utils/utils.py", line 36, in <listcomp>
        return [json.loads(line) for line in fh.readlines() if line]
      File "/cluster/project/sachan/yifan/softwares/anaconda/anaconda3/envs/llama/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/cluster/project/sachan/yifan/softwares/anaconda/anaconda3/envs/llama/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/cluster/project/sachan/yifan/softwares/anaconda/anaconda3/envs/llama/lib/python3.9/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

When I checked the file (e.g., `data/aqua_rat/aqua_rat_graph_annotation_train.jsonl`), it contains some invalid oid of Git-LFS. 

    version https://git-lfs.github.com/spec/v1
    oid sha256:42de0109f6f0efdd813f18a018b8eba747483f0b07874f6b9b11fbae8db985cd
    size 245085

Could you take a look?

Best,
Yifan

**Comment by henghui-zhu-amazon** [comment]
Hi Yifan,

Would you mind installing git-lfs first and try to pull the repo again? For example, in macOS, you can do `brew install git-lfs` first. And in Ubuntu, you can do `apt-get install git-lfs`. Then you run `git lfs install` before you do `git clone`. 

I believe after you install the git lfs, you should be able to clone the repo correctly.

Best,
Henghui Zhu

**Comment by yifan-h** [comment]
Hi Henghui,

Thanks for the help! The environment that I'm using is quite old, and some
errors happened when I install it. But no worries, I manually download the
raw annotation files and it works now.

Many thanks to you!!! And hope there will be more wonderful work from you
in the future.

Best,
Yifan
